// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Domain is the predicate function for domain builders.
type Domain func(*sql.Selector)

// ProviderKey is the predicate function for providerkey builders.
type ProviderKey func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
