// Code generated by ent, DO NOT EDIT.

package ent

import (
	"domain-manager/ent/providerkey"
	"domain-manager/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ProviderKey is the model entity for the ProviderKey schema.
type ProviderKey struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// AccessKey holds the value of the "access_key" field.
	AccessKey string `json:"access_key,omitempty"`
	// SecretKey holds the value of the "secret_key" field.
	SecretKey string `json:"secret_key,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProviderKeyQuery when eager-loading is set.
	Edges              ProviderKeyEdges `json:"edges"`
	user_provider_keys *int
	selectValues       sql.SelectValues
}

// ProviderKeyEdges holds the relations/edges for other nodes in the graph.
type ProviderKeyEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProviderKeyEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providerkey.FieldID:
			values[i] = new(sql.NullInt64)
		case providerkey.FieldName, providerkey.FieldProvider, providerkey.FieldAccessKey, providerkey.FieldSecretKey:
			values[i] = new(sql.NullString)
		case providerkey.FieldCreatedAt, providerkey.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case providerkey.ForeignKeys[0]: // user_provider_keys
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderKey fields.
func (pk *ProviderKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providerkey.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pk.ID = int(value.Int64)
		case providerkey.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				pk.Name = value.String
			}
		case providerkey.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				pk.Provider = value.String
			}
		case providerkey.FieldAccessKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_key", values[i])
			} else if value.Valid {
				pk.AccessKey = value.String
			}
		case providerkey.FieldSecretKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_key", values[i])
			} else if value.Valid {
				pk.SecretKey = value.String
			}
		case providerkey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pk.CreatedAt = value.Time
			}
		case providerkey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pk.UpdatedAt = value.Time
			}
		case providerkey.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_provider_keys", value)
			} else if value.Valid {
				pk.user_provider_keys = new(int)
				*pk.user_provider_keys = int(value.Int64)
			}
		default:
			pk.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderKey.
// This includes values selected through modifiers, order, etc.
func (pk *ProviderKey) Value(name string) (ent.Value, error) {
	return pk.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ProviderKey entity.
func (pk *ProviderKey) QueryUser() *UserQuery {
	return NewProviderKeyClient(pk.config).QueryUser(pk)
}

// Update returns a builder for updating this ProviderKey.
// Note that you need to call ProviderKey.Unwrap() before calling this method if this ProviderKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (pk *ProviderKey) Update() *ProviderKeyUpdateOne {
	return NewProviderKeyClient(pk.config).UpdateOne(pk)
}

// Unwrap unwraps the ProviderKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pk *ProviderKey) Unwrap() *ProviderKey {
	_tx, ok := pk.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderKey is not a transactional entity")
	}
	pk.config.driver = _tx.drv
	return pk
}

// String implements the fmt.Stringer.
func (pk *ProviderKey) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pk.ID))
	builder.WriteString("name=")
	builder.WriteString(pk.Name)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(pk.Provider)
	builder.WriteString(", ")
	builder.WriteString("access_key=")
	builder.WriteString(pk.AccessKey)
	builder.WriteString(", ")
	builder.WriteString("secret_key=")
	builder.WriteString(pk.SecretKey)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pk.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(pk.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProviderKeys is a parsable slice of ProviderKey.
type ProviderKeys []*ProviderKey
