// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"domain-manager/ent/predicate"
	"domain-manager/ent/providerkey"
	"domain-manager/ent/user"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProviderKeyQuery is the builder for querying ProviderKey entities.
type ProviderKeyQuery struct {
	config
	ctx        *QueryContext
	order      []providerkey.OrderOption
	inters     []Interceptor
	predicates []predicate.ProviderKey
	withUser   *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProviderKeyQuery builder.
func (pkq *ProviderKeyQuery) Where(ps ...predicate.ProviderKey) *ProviderKeyQuery {
	pkq.predicates = append(pkq.predicates, ps...)
	return pkq
}

// Limit the number of records to be returned by this query.
func (pkq *ProviderKeyQuery) Limit(limit int) *ProviderKeyQuery {
	pkq.ctx.Limit = &limit
	return pkq
}

// Offset to start from.
func (pkq *ProviderKeyQuery) Offset(offset int) *ProviderKeyQuery {
	pkq.ctx.Offset = &offset
	return pkq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pkq *ProviderKeyQuery) Unique(unique bool) *ProviderKeyQuery {
	pkq.ctx.Unique = &unique
	return pkq
}

// Order specifies how the records should be ordered.
func (pkq *ProviderKeyQuery) Order(o ...providerkey.OrderOption) *ProviderKeyQuery {
	pkq.order = append(pkq.order, o...)
	return pkq
}

// QueryUser chains the current query on the "user" edge.
func (pkq *ProviderKeyQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: pkq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pkq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pkq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(providerkey.Table, providerkey.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, providerkey.UserTable, providerkey.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(pkq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProviderKey entity from the query.
// Returns a *NotFoundError when no ProviderKey was found.
func (pkq *ProviderKeyQuery) First(ctx context.Context) (*ProviderKey, error) {
	nodes, err := pkq.Limit(1).All(setContextOp(ctx, pkq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{providerkey.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pkq *ProviderKeyQuery) FirstX(ctx context.Context) *ProviderKey {
	node, err := pkq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProviderKey ID from the query.
// Returns a *NotFoundError when no ProviderKey ID was found.
func (pkq *ProviderKeyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pkq.Limit(1).IDs(setContextOp(ctx, pkq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{providerkey.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pkq *ProviderKeyQuery) FirstIDX(ctx context.Context) int {
	id, err := pkq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProviderKey entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProviderKey entity is found.
// Returns a *NotFoundError when no ProviderKey entities are found.
func (pkq *ProviderKeyQuery) Only(ctx context.Context) (*ProviderKey, error) {
	nodes, err := pkq.Limit(2).All(setContextOp(ctx, pkq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{providerkey.Label}
	default:
		return nil, &NotSingularError{providerkey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pkq *ProviderKeyQuery) OnlyX(ctx context.Context) *ProviderKey {
	node, err := pkq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProviderKey ID in the query.
// Returns a *NotSingularError when more than one ProviderKey ID is found.
// Returns a *NotFoundError when no entities are found.
func (pkq *ProviderKeyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pkq.Limit(2).IDs(setContextOp(ctx, pkq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{providerkey.Label}
	default:
		err = &NotSingularError{providerkey.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pkq *ProviderKeyQuery) OnlyIDX(ctx context.Context) int {
	id, err := pkq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProviderKeys.
func (pkq *ProviderKeyQuery) All(ctx context.Context) ([]*ProviderKey, error) {
	ctx = setContextOp(ctx, pkq.ctx, "All")
	if err := pkq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProviderKey, *ProviderKeyQuery]()
	return withInterceptors[[]*ProviderKey](ctx, pkq, qr, pkq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pkq *ProviderKeyQuery) AllX(ctx context.Context) []*ProviderKey {
	nodes, err := pkq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProviderKey IDs.
func (pkq *ProviderKeyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pkq.ctx.Unique == nil && pkq.path != nil {
		pkq.Unique(true)
	}
	ctx = setContextOp(ctx, pkq.ctx, "IDs")
	if err = pkq.Select(providerkey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pkq *ProviderKeyQuery) IDsX(ctx context.Context) []int {
	ids, err := pkq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pkq *ProviderKeyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pkq.ctx, "Count")
	if err := pkq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pkq, querierCount[*ProviderKeyQuery](), pkq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pkq *ProviderKeyQuery) CountX(ctx context.Context) int {
	count, err := pkq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pkq *ProviderKeyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pkq.ctx, "Exist")
	switch _, err := pkq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pkq *ProviderKeyQuery) ExistX(ctx context.Context) bool {
	exist, err := pkq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProviderKeyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pkq *ProviderKeyQuery) Clone() *ProviderKeyQuery {
	if pkq == nil {
		return nil
	}
	return &ProviderKeyQuery{
		config:     pkq.config,
		ctx:        pkq.ctx.Clone(),
		order:      append([]providerkey.OrderOption{}, pkq.order...),
		inters:     append([]Interceptor{}, pkq.inters...),
		predicates: append([]predicate.ProviderKey{}, pkq.predicates...),
		withUser:   pkq.withUser.Clone(),
		// clone intermediate query.
		sql:  pkq.sql.Clone(),
		path: pkq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (pkq *ProviderKeyQuery) WithUser(opts ...func(*UserQuery)) *ProviderKeyQuery {
	query := (&UserClient{config: pkq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pkq.withUser = query
	return pkq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProviderKey.Query().
//		GroupBy(providerkey.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pkq *ProviderKeyQuery) GroupBy(field string, fields ...string) *ProviderKeyGroupBy {
	pkq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProviderKeyGroupBy{build: pkq}
	grbuild.flds = &pkq.ctx.Fields
	grbuild.label = providerkey.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ProviderKey.Query().
//		Select(providerkey.FieldName).
//		Scan(ctx, &v)
func (pkq *ProviderKeyQuery) Select(fields ...string) *ProviderKeySelect {
	pkq.ctx.Fields = append(pkq.ctx.Fields, fields...)
	sbuild := &ProviderKeySelect{ProviderKeyQuery: pkq}
	sbuild.label = providerkey.Label
	sbuild.flds, sbuild.scan = &pkq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProviderKeySelect configured with the given aggregations.
func (pkq *ProviderKeyQuery) Aggregate(fns ...AggregateFunc) *ProviderKeySelect {
	return pkq.Select().Aggregate(fns...)
}

func (pkq *ProviderKeyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pkq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pkq); err != nil {
				return err
			}
		}
	}
	for _, f := range pkq.ctx.Fields {
		if !providerkey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pkq.path != nil {
		prev, err := pkq.path(ctx)
		if err != nil {
			return err
		}
		pkq.sql = prev
	}
	return nil
}

func (pkq *ProviderKeyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProviderKey, error) {
	var (
		nodes       = []*ProviderKey{}
		withFKs     = pkq.withFKs
		_spec       = pkq.querySpec()
		loadedTypes = [1]bool{
			pkq.withUser != nil,
		}
	)
	if pkq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, providerkey.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProviderKey).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProviderKey{config: pkq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pkq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pkq.withUser; query != nil {
		if err := pkq.loadUser(ctx, query, nodes, nil,
			func(n *ProviderKey, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pkq *ProviderKeyQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*ProviderKey, init func(*ProviderKey), assign func(*ProviderKey, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ProviderKey)
	for i := range nodes {
		if nodes[i].user_provider_keys == nil {
			continue
		}
		fk := *nodes[i].user_provider_keys
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_provider_keys" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pkq *ProviderKeyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pkq.querySpec()
	_spec.Node.Columns = pkq.ctx.Fields
	if len(pkq.ctx.Fields) > 0 {
		_spec.Unique = pkq.ctx.Unique != nil && *pkq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pkq.driver, _spec)
}

func (pkq *ProviderKeyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(providerkey.Table, providerkey.Columns, sqlgraph.NewFieldSpec(providerkey.FieldID, field.TypeInt))
	_spec.From = pkq.sql
	if unique := pkq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pkq.path != nil {
		_spec.Unique = true
	}
	if fields := pkq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providerkey.FieldID)
		for i := range fields {
			if fields[i] != providerkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pkq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pkq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pkq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pkq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pkq *ProviderKeyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pkq.driver.Dialect())
	t1 := builder.Table(providerkey.Table)
	columns := pkq.ctx.Fields
	if len(columns) == 0 {
		columns = providerkey.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pkq.sql != nil {
		selector = pkq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pkq.ctx.Unique != nil && *pkq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pkq.predicates {
		p(selector)
	}
	for _, p := range pkq.order {
		p(selector)
	}
	if offset := pkq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pkq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProviderKeyGroupBy is the group-by builder for ProviderKey entities.
type ProviderKeyGroupBy struct {
	selector
	build *ProviderKeyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pkgb *ProviderKeyGroupBy) Aggregate(fns ...AggregateFunc) *ProviderKeyGroupBy {
	pkgb.fns = append(pkgb.fns, fns...)
	return pkgb
}

// Scan applies the selector query and scans the result into the given value.
func (pkgb *ProviderKeyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pkgb.build.ctx, "GroupBy")
	if err := pkgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProviderKeyQuery, *ProviderKeyGroupBy](ctx, pkgb.build, pkgb, pkgb.build.inters, v)
}

func (pkgb *ProviderKeyGroupBy) sqlScan(ctx context.Context, root *ProviderKeyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pkgb.fns))
	for _, fn := range pkgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pkgb.flds)+len(pkgb.fns))
		for _, f := range *pkgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pkgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pkgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProviderKeySelect is the builder for selecting fields of ProviderKey entities.
type ProviderKeySelect struct {
	*ProviderKeyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pks *ProviderKeySelect) Aggregate(fns ...AggregateFunc) *ProviderKeySelect {
	pks.fns = append(pks.fns, fns...)
	return pks
}

// Scan applies the selector query and scans the result into the given value.
func (pks *ProviderKeySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pks.ctx, "Select")
	if err := pks.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProviderKeyQuery, *ProviderKeySelect](ctx, pks.ProviderKeyQuery, pks, pks.inters, v)
}

func (pks *ProviderKeySelect) sqlScan(ctx context.Context, root *ProviderKeyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pks.fns))
	for _, fn := range pks.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pks.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
