// Code generated by ent, DO NOT EDIT.

package ent

import (
	"domain-manager/ent/domain"
	"domain-manager/ent/providerkey"
	"domain-manager/ent/schema"
	"domain-manager/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	domainFields := schema.Domain{}.Fields()
	_ = domainFields
	// domainDescName is the schema descriptor for name field.
	domainDescName := domainFields[1].Descriptor()
	// domain.NameValidator is a validator for the "name" field. It is called by the builders before save.
	domain.NameValidator = domainDescName.Validators[0].(func(string) error)
	// domainDescProvider is the schema descriptor for provider field.
	domainDescProvider := domainFields[2].Descriptor()
	// domain.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	domain.ProviderValidator = domainDescProvider.Validators[0].(func(string) error)
	// domainDescID is the schema descriptor for id field.
	domainDescID := domainFields[0].Descriptor()
	// domain.IDValidator is a validator for the "id" field. It is called by the builders before save.
	domain.IDValidator = domainDescID.Validators[0].(func(int) error)
	providerkeyFields := schema.ProviderKey{}.Fields()
	_ = providerkeyFields
	// providerkeyDescName is the schema descriptor for name field.
	providerkeyDescName := providerkeyFields[1].Descriptor()
	// providerkey.DefaultName holds the default value on creation for the name field.
	providerkey.DefaultName = providerkeyDescName.Default.(string)
	// providerkey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	providerkey.NameValidator = providerkeyDescName.Validators[0].(func(string) error)
	// providerkeyDescProvider is the schema descriptor for provider field.
	providerkeyDescProvider := providerkeyFields[2].Descriptor()
	// providerkey.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	providerkey.ProviderValidator = providerkeyDescProvider.Validators[0].(func(string) error)
	// providerkeyDescAccessKey is the schema descriptor for access_key field.
	providerkeyDescAccessKey := providerkeyFields[3].Descriptor()
	// providerkey.AccessKeyValidator is a validator for the "access_key" field. It is called by the builders before save.
	providerkey.AccessKeyValidator = providerkeyDescAccessKey.Validators[0].(func(string) error)
	// providerkeyDescID is the schema descriptor for id field.
	providerkeyDescID := providerkeyFields[0].Descriptor()
	// providerkey.IDValidator is a validator for the "id" field. It is called by the builders before save.
	providerkey.IDValidator = providerkeyDescID.Validators[0].(func(int) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(int) error)
}
